### PR TITLE
get_max_fraction() and get_min_fraction() instead of 1 and 0

### PR DESCRIPTION
**Pull request by vadimonus**
I suggest that it's better to use get_max_fraction() and get_min_fraction() instead of 1 and 0. Builtin question types returns 1 and 0, but maybe some custom types may use other max and min value.
When comparing fraction to 1 tolerance must be taking into account. If you have 3 rights answers with 0.3333333 they give 0.9999999, resulting in not right answer instead of right

### CODE REVIEW

**Comment by dthies** [comment]
@vadimonus @JasonEverling I as sorry I have not merged this yet. I am fine doing that, but I do not exactly understand how to reproduce the problem. Do either of you have a specific question for me to use as a test case? I should add some automated tests for this.

**Comment by JasonEverling** [comment]
@dthies Question below, pretty simple. Even if they answer a,b,e which should mark it correct but ends up marking it wrong

Which values add up to 12? Select all that apply
a. 8
b. 2
c. 6
d. 7
e. 2

Answers: a,b,e

**Comment by dthies** [comment]
It looks as this is a multiple choice with Multiple answers allowed so I created it and gave correct answers 33.3333% each and tested with the most recent version of my plugin and Moodle. Checked the correct answers and submitted and received a correct result.  Am I missing something?
Screenshot_2019-08-12_18-33-54

**Comment by JasonEverling** [comment]
That looks about right, i am not sure why all of ours were being marked incorrect. We are on 3.5+ and have the latest version of your plugin. Maybe they were not all set to 33.3333% by the instructor? Would marking them with a different % even make a difference?

**Comment by JasonEverling** [comment]
an update, actually the issue is when they select the 3 right anwers and then also select an additional wrong answer they still get it right

**Comment by JasonEverling** [comment]
if the put a negative percent for the wrong asnwers it gets graded correctly

**Comment by dthies** [comment]
I fixed this issue some time ago by checking question_state::get_grade_state_for_fraction so I will close this now.

**Pull request closed without merging**
